# Generated by Django 3.0.6 on 2020-05-08 22:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=250)),
                ('urlToImage', models.CharField(max_length=250)),
                ('publishedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
